# Generated by Django 4.1.1 on 2022-09-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_blogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='blog',
            field=models.TextField(),
        ),
    ]
